-- 300 new products across the same 8 categories as V14 -- evenly distributed
-- (see the requesting conversation: testing catalog-scale behavior, not a real business
-- need). Same format as V14, continuing its id range (V14 ended at 57).
-- Category counts: Electronics 38, Home & Kitchen 38, Sports & Outdoors 38, Books 38, Fashion 37, Toys & Games 37, Beauty 37, Office 37 (300 total, ids 58-357).
INSERT INTO product (id, sku, name, unit_price, category) VALUES (58, 'ELEC-58', 'Dual-Band Earbuds', 59.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (59, 'ELEC-59', 'Bluetooth Monitor', 38.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (60, 'ELEC-60', 'Dual-Band Smart Plug', 306.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (61, 'ELEC-61', 'Dual-Band Webcam', 230.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (62, 'ELEC-62', 'Digital LED Strip Light', 55.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (63, 'ELEC-63', 'USB-C Monitor', 148.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (64, 'ELEC-64', 'Digital Earbuds', 256.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (65, 'ELEC-65', 'Wireless Router', 217.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (66, 'ELEC-66', 'Portable USB Hub', 156.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (67, 'ELEC-67', 'USB-C Webcam', 114.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (68, 'ELEC-68', 'Bluetooth Tablet Stand', 167.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (69, 'ELEC-69', '4K Webcam', 181.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (70, 'ELEC-70', 'Fast-Charging LED Strip Light', 54.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (71, 'ELEC-71', 'USB-C Mini Projector', 303.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (72, 'ELEC-72', 'Rechargeable Docking Station', 144.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (73, 'ELEC-73', '4K Docking Station', 265.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (74, 'ELEC-74', 'Portable Power Bank', 83.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (75, 'ELEC-75', 'Compact Webcam', 41.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (76, 'ELEC-76', 'Digital Charging Pad', 215.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (77, 'ELEC-77', 'Wireless Mouse', 260.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (78, 'ELEC-78', 'HD Power Bank', 36.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (79, 'ELEC-79', 'Wireless Earbuds', 93.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (80, 'ELEC-80', 'Fast-Charging Mouse', 185.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (81, 'ELEC-81', 'Portable Mini Projector', 134.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (82, 'ELEC-82', 'Compact Speaker', 268.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (83, 'ELEC-83', 'Fast-Charging Monitor', 303.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (84, 'ELEC-84', 'Portable Smart Plug', 171.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (85, 'ELEC-85', 'Rechargeable Earbuds', 223.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (86, 'ELEC-86', 'Compact Charger', 108.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (87, 'ELEC-87', 'Smart Monitor', 181.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (88, 'ELEC-88', 'Digital Speaker', 180.00, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (89, 'ELEC-89', 'Fast-Charging Router', 248.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (90, 'ELEC-90', 'USB-C Router', 217.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (91, 'ELEC-91', 'USB-C Keyboard', 282.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (92, 'ELEC-92', 'Fast-Charging Keyboard', 139.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (93, 'ELEC-93', 'Compact Router', 269.50, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (94, 'ELEC-94', '4K Keyboard', 225.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (95, 'ELEC-95', 'Fast-Charging Charger', 308.99, 'Electronics');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (96, 'HOME-96', 'Ceramic Knife Set', 17.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (97, 'HOME-97', 'Insulated Dish Rack', 90.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (98, 'HOME-98', 'Automatic Trash Can', 156.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (99, 'HOME-99', 'Multi-Function Blender', 206.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (100, 'HOME-100', 'Stainless Steel Food Storage Set', 175.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (101, 'HOME-101', 'Digital Slow Cooker', 195.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (102, 'HOME-102', 'Multi-Function Dish Rack', 257.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (103, 'HOME-103', 'Glass Toaster', 269.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (104, 'HOME-104', 'Stainless Steel Humidifier', 64.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (105, 'HOME-105', 'Ceramic Humidifier', 221.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (106, 'HOME-106', 'Insulated Mixing Bowl Set', 180.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (107, 'HOME-107', 'Cordless Hand Mixer', 250.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (108, 'HOME-108', 'Non-Stick Trash Can', 41.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (109, 'HOME-109', 'Automatic Air Purifier', 22.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (110, 'HOME-110', 'Insulated Rice Cooker', 241.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (111, 'HOME-111', 'Stainless Steel Rice Cooker', 137.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (112, 'HOME-112', 'Automatic Food Storage Set', 73.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (113, 'HOME-113', 'Digital Bakeware Set', 27.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (114, 'HOME-114', 'Compact Trash Can', 274.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (115, 'HOME-115', 'Compact Knife Set', 193.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (116, 'HOME-116', 'Ceramic Mixing Bowl Set', 72.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (117, 'HOME-117', 'Compact Bakeware Set', 238.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (118, 'HOME-118', 'Multi-Function Toaster', 303.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (119, 'HOME-119', 'Cordless Food Storage Set', 116.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (120, 'HOME-120', 'Electric Food Storage Set', 286.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (121, 'HOME-121', 'Compact Food Storage Set', 292.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (122, 'HOME-122', 'Cordless Bakeware Set', 84.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (123, 'HOME-123', 'Cast Iron Mixing Bowl Set', 314.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (124, 'HOME-124', 'Multi-Function Humidifier', 18.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (125, 'HOME-125', 'Cast Iron Blender', 317.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (126, 'HOME-126', 'Non-Stick Food Storage Set', 81.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (127, 'HOME-127', 'Electric Air Purifier', 170.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (128, 'HOME-128', 'Cast Iron Food Storage Set', 100.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (129, 'HOME-129', 'Cast Iron Hand Mixer', 109.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (130, 'HOME-130', 'Glass Food Storage Set', 149.99, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (131, 'HOME-131', 'Glass Coffee Maker', 289.00, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (132, 'HOME-132', 'Compact Blender', 285.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (133, 'HOME-133', 'Insulated Kettle', 148.50, 'Home & Kitchen');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (134, 'SPRT-134', 'Insulated Hiking Backpack', 25.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (135, 'SPRT-135', 'Non-Slip Running Shoes', 55.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (136, 'SPRT-136', 'Compact Hiking Backpack', 67.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (137, 'SPRT-137', 'Portable Resistance Bands', 173.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (138, 'SPRT-138', 'Foldable Dumbbell Set', 135.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (139, 'SPRT-139', 'Quick-Dry Hiking Backpack', 54.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (140, 'SPRT-140', 'Quick-Dry Trekking Poles', 44.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (141, 'SPRT-141', 'All-Weather Camping Chair', 35.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (142, 'SPRT-142', 'Foldable Cooler Box', 145.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (143, 'SPRT-143', 'Waterproof Jump Rope', 103.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (144, 'SPRT-144', 'Foldable Yoga Mat', 118.50, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (145, 'SPRT-145', 'Non-Slip Yoga Mat', 142.50, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (146, 'SPRT-146', 'Reflective Resistance Bands', 123.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (147, 'SPRT-147', 'All-Weather Running Shoes', 111.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (148, 'SPRT-148', 'Foldable Resistance Bands', 79.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (149, 'SPRT-149', 'Heavy-Duty Jump Rope', 125.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (150, 'SPRT-150', 'Lightweight Kettlebell', 119.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (151, 'SPRT-151', 'Reflective Jump Rope', 178.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (152, 'SPRT-152', 'Waterproof Cooler Box', 110.50, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (153, 'SPRT-153', 'Foldable Cycling Gloves', 155.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (154, 'SPRT-154', 'Non-Slip Exercise Bike', 112.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (155, 'SPRT-155', 'Quick-Dry Yoga Mat', 133.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (156, 'SPRT-156', 'Adjustable Bike Helmet', 38.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (157, 'SPRT-157', 'Portable Camping Tent', 91.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (158, 'SPRT-158', 'Insulated Dumbbell Set', 147.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (159, 'SPRT-159', 'Adjustable Kettlebell', 71.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (160, 'SPRT-160', 'Lightweight Fishing Rod', 132.50, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (161, 'SPRT-161', 'Portable Dumbbell Set', 92.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (162, 'SPRT-162', 'Insulated Camping Chair', 117.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (163, 'SPRT-163', 'Heavy-Duty Kettlebell', 145.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (164, 'SPRT-164', 'All-Weather Cooler Box', 96.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (165, 'SPRT-165', 'Non-Slip Sleeping Bag', 173.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (166, 'SPRT-166', 'Lightweight Cycling Gloves', 158.50, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (167, 'SPRT-167', 'Quick-Dry Dumbbell Set', 50.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (168, 'SPRT-168', 'Non-Slip Hiking Backpack', 75.50, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (169, 'SPRT-169', 'Foldable Hiking Backpack', 78.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (170, 'SPRT-170', 'Lightweight Running Shoes', 16.99, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (171, 'SPRT-171', 'Waterproof Bike Helmet', 173.00, 'Sports & Outdoors');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (172, 'BOOK-172', 'The Midnight Library', 16.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (173, 'BOOK-173', 'Educated', 19.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (174, 'BOOK-174', 'The Silent Patient', 33.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (175, 'BOOK-175', 'Thinking, Fast and Slow', 16.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (176, 'BOOK-176', 'Project Hail Mary', 44.50, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (177, 'BOOK-177', 'The Alchemist', 36.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (178, 'BOOK-178', 'Where the Crawdads Sing', 25.50, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (179, 'BOOK-179', 'The Design of Everyday Things', 27.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (180, 'BOOK-180', 'Clean Architecture', 33.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (181, 'BOOK-181', 'Dune', 38.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (182, 'BOOK-182', '1984', 21.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (183, 'BOOK-183', 'To Kill a Mockingbird', 12.50, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (184, 'BOOK-184', 'The Hobbit', 19.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (185, 'BOOK-185', 'The Power of Habit', 11.50, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (186, 'BOOK-186', 'Zero to One', 17.50, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (187, 'BOOK-187', 'The Lean Startup', 28.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (188, 'BOOK-188', 'Man''s Search for Meaning', 15.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (189, 'BOOK-189', 'The Subtle Art of Not Giving a F*ck', 37.50, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (190, 'BOOK-190', 'Rich Dad Poor Dad', 19.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (191, 'BOOK-191', 'The Catcher in the Rye', 26.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (192, 'BOOK-192', 'Brave New World', 31.50, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (193, 'BOOK-193', 'The Road', 44.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (194, 'BOOK-194', 'Norwegian Wood', 42.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (195, 'BOOK-195', 'The Martian', 22.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (196, 'BOOK-196', 'Circe', 27.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (197, 'BOOK-197', 'The Night Circus', 44.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (198, 'BOOK-198', 'A Gentleman in Moscow', 44.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (199, 'BOOK-199', 'The Kite Runner', 12.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (200, 'BOOK-200', 'Life of Pi', 32.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (201, 'BOOK-201', 'The Girl on the Train', 36.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (202, 'BOOK-202', 'Gone Girl', 38.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (203, 'BOOK-203', 'The Book Thief', 42.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (204, 'BOOK-204', 'Fahrenheit 451', 10.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (205, 'BOOK-205', 'The Fault in Our Stars', 36.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (206, 'BOOK-206', 'Becoming', 17.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (207, 'BOOK-207', 'Outliers', 10.99, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (208, 'BOOK-208', 'The Innovator''s Dilemma', 43.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (209, 'BOOK-209', 'Grokking Algorithms', 21.00, 'Books');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (210, 'FASH-210', 'Casual Sunglasses', 126.00, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (211, 'FASH-211', 'Men''s Belt', 65.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (212, 'FASH-212', 'Classic Hoodie', 22.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (213, 'FASH-213', 'Relaxed Fit Scarf', 31.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (214, 'FASH-214', 'Men''s Chino Pants', 83.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (215, 'FASH-215', 'Women''s Wallet', 94.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (216, 'FASH-216', 'Vintage Wallet', 89.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (217, 'FASH-217', 'Unisex Rain Jacket', 123.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (218, 'FASH-218', 'Unisex Wool Coat', 53.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (219, 'FASH-219', 'Relaxed Fit Beanie Hat', 53.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (220, 'FASH-220', 'Vintage Scarf', 102.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (221, 'FASH-221', 'Casual Belt', 28.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (222, 'FASH-222', 'Unisex Backpack', 72.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (223, 'FASH-223', 'Vintage Puffer Vest', 99.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (224, 'FASH-224', 'Vintage Sunglasses', 88.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (225, 'FASH-225', 'Leather Backpack', 30.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (226, 'FASH-226', 'Slim Fit Scarf', 71.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (227, 'FASH-227', 'Vintage Chino Pants', 78.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (228, 'FASH-228', 'Waterproof T-Shirt', 29.00, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (229, 'FASH-229', 'Quilted Backpack', 78.00, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (230, 'FASH-230', 'Women''s Crossbody Bag', 31.00, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (231, 'FASH-231', 'Women''s Baseball Cap', 22.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (232, 'FASH-232', 'Leather Sneakers', 27.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (233, 'FASH-233', 'Leather Belt', 74.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (234, 'FASH-234', 'Quilted Ankle Boots', 64.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (235, 'FASH-235', 'Casual Scarf', 45.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (236, 'FASH-236', 'Casual Backpack', 26.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (237, 'FASH-237', 'Relaxed Fit Baseball Cap', 30.00, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (238, 'FASH-238', 'Casual Rain Jacket', 74.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (239, 'FASH-239', 'Men''s Baseball Cap', 58.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (240, 'FASH-240', 'Casual Canvas Tote Bag', 63.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (241, 'FASH-241', 'Leather Hoodie', 24.00, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (242, 'FASH-242', 'Quilted Wool Coat', 101.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (243, 'FASH-243', 'Men''s Crossbody Bag', 46.50, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (244, 'FASH-244', 'Waterproof Sunglasses', 32.00, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (245, 'FASH-245', 'Waterproof Wallet', 16.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (246, 'FASH-246', 'Men''s Wool Coat', 75.99, 'Fashion');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (247, 'TOYS-247', 'Family RC Car', 44.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (248, 'TOYS-248', '3D Jigsaw Puzzle', 65.50, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (249, 'TOYS-249', 'Light-Up Building Bricks Set', 62.50, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (250, 'TOYS-250', 'Glow-in-the-Dark Yo-Yo', 31.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (251, 'TOYS-251', 'Classic Yo-Yo', 41.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (252, 'TOYS-252', 'Classic Playing Cards', 38.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (253, 'TOYS-253', 'Classic Puzzle Cube', 23.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (254, 'TOYS-254', 'Family Board Game Night Bundle', 40.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (255, 'TOYS-255', 'Light-Up Building Blocks Set', 26.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (256, 'TOYS-256', 'Magnetic Toy Kitchen Set', 65.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (257, 'TOYS-257', 'Interactive Toy Kitchen Set', 29.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (258, 'TOYS-258', 'Deluxe Water Gun', 57.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (259, 'TOYS-259', 'Light-Up Action Figure', 22.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (260, 'TOYS-260', 'Light-Up RC Car', 63.50, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (261, 'TOYS-261', 'Deluxe Teddy Bear', 58.50, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (262, 'TOYS-262', 'Deluxe Dollhouse', 35.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (263, 'TOYS-263', 'Deluxe Building Blocks Set', 61.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (264, 'TOYS-264', 'Educational Building Blocks Set', 52.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (265, 'TOYS-265', 'Light-Up Yo-Yo', 49.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (266, 'TOYS-266', '3D Building Blocks Set', 12.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (267, 'TOYS-267', '3D Water Gun', 66.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (268, 'TOYS-268', 'Miniature Teddy Bear', 58.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (269, 'TOYS-269', '3D Toy Kitchen Set', 52.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (270, 'TOYS-270', 'Glow-in-the-Dark Puzzle Cube', 68.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (271, 'TOYS-271', 'Miniature Kite', 16.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (272, 'TOYS-272', 'Miniature Building Blocks Set', 61.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (273, 'TOYS-273', 'Classic Toy Kitchen Set', 6.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (274, 'TOYS-274', 'Wooden Playing Cards', 62.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (275, 'TOYS-275', 'Family Playing Cards', 61.50, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (276, 'TOYS-276', 'Educational Play Tent', 17.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (277, 'TOYS-277', 'Glow-in-the-Dark Building Blocks Set', 41.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (278, 'TOYS-278', 'Glow-in-the-Dark Board Game', 41.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (279, 'TOYS-279', 'Deluxe Puzzle Cube', 16.00, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (280, 'TOYS-280', 'Deluxe Play Tent', 48.50, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (281, 'TOYS-281', 'Magnetic Action Figure', 45.50, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (282, 'TOYS-282', 'Family Toy Kitchen Set', 11.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (283, 'TOYS-283', 'Wooden Yo-Yo', 26.99, 'Toys & Games');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (284, 'BEAU-284', 'Nourishing Eyeliner', 10.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (285, 'BEAU-285', 'Vitamin C Lip Balm', 40.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (286, 'BEAU-286', 'Natural Sunscreen', 37.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (287, 'BEAU-287', 'Nourishing Body Scrub', 41.50, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (288, 'BEAU-288', 'Gentle Cleansing Foam', 44.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (289, 'BEAU-289', 'Gentle Perfume', 29.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (290, 'BEAU-290', 'Vitamin C Setting Spray', 45.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (291, 'BEAU-291', 'Waterproof Setting Spray', 52.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (292, 'BEAU-292', 'Long-Lasting Moisturizer', 46.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (293, 'BEAU-293', 'Vitamin C Hair Serum', 21.50, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (294, 'BEAU-294', 'Organic Eyeliner', 44.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (295, 'BEAU-295', 'Brightening Face Mask Set', 32.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (296, 'BEAU-296', 'Hydrating Moisturizer', 18.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (297, 'BEAU-297', 'Natural Face Mask Set', 41.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (298, 'BEAU-298', 'Organic Body Scrub', 55.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (299, 'BEAU-299', 'Anti-Aging Nail Polish Set', 19.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (300, 'BEAU-300', 'Vitamin C Face Mask Set', 20.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (301, 'BEAU-301', 'Vitamin C Makeup Brush Set', 40.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (302, 'BEAU-302', 'Matte Hair Dryer', 16.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (303, 'BEAU-303', 'Natural Hair Dryer', 14.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (304, 'BEAU-304', 'Fragrance-Free Moisturizer', 14.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (305, 'BEAU-305', 'Brightening Makeup Brush Set', 46.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (306, 'BEAU-306', 'Organic Setting Spray', 28.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (307, 'BEAU-307', 'Anti-Aging Eyeshadow Palette', 9.50, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (308, 'BEAU-308', 'Long-Lasting Hair Dryer', 56.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (309, 'BEAU-309', 'Hydrating Eyeliner', 54.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (310, 'BEAU-310', 'Matte Moisturizer', 33.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (311, 'BEAU-311', 'Matte Perfume', 11.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (312, 'BEAU-312', 'Matte Hair Serum', 36.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (313, 'BEAU-313', 'Waterproof Perfume', 24.50, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (314, 'BEAU-314', 'Hydrating Hair Serum', 56.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (315, 'BEAU-315', 'Natural Setting Spray', 49.00, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (316, 'BEAU-316', 'Hydrating Lip Balm', 37.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (317, 'BEAU-317', 'Long-Lasting Lip Balm', 38.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (318, 'BEAU-318', 'Waterproof Facial Serum', 27.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (319, 'BEAU-319', 'Waterproof Body Scrub', 33.50, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (320, 'BEAU-320', 'Matte Face Mask Set', 24.99, 'Beauty');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (321, 'OFFC-321', 'Rechargeable Stapler', 261.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (322, 'OFFC-322', 'Compact Bulletin Board', 75.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (323, 'OFFC-323', 'Wireless Desk Lamp', 135.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (324, 'OFFC-324', 'Adjustable Office Chair', 66.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (325, 'OFFC-325', 'LED Cable Organizer', 30.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (326, 'OFFC-326', 'LED Bookend Set', 258.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (327, 'OFFC-327', 'Compact Stapler', 306.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (328, 'OFFC-328', 'Adjustable Standing Desk', 166.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (329, 'OFFC-329', 'Compact Cable Organizer', 257.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (330, 'OFFC-330', 'Space-Saving Label Maker', 25.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (331, 'OFFC-331', 'Adjustable Monitor Stand', 315.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (332, 'OFFC-332', 'Executive Filing Cabinet', 81.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (333, 'OFFC-333', 'Space-Saving Monitor Stand', 231.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (334, 'OFFC-334', 'Wireless Office Chair', 158.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (335, 'OFFC-335', 'Rechargeable Document Scanner', 233.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (336, 'OFFC-336', 'LED Bulletin Board', 26.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (337, 'OFFC-337', 'Portable Whiteboard', 185.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (338, 'OFFC-338', 'LED Desk Lamp', 85.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (339, 'OFFC-339', 'Multi-Function Desk Organizer', 46.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (340, 'OFFC-340', 'Heavy-Duty Filing Cabinet', 145.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (341, 'OFFC-341', 'Space-Saving Bulletin Board', 121.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (342, 'OFFC-342', 'Multi-Function Cable Organizer', 291.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (343, 'OFFC-343', 'Rechargeable Paper Shredder', 81.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (344, 'OFFC-344', 'Adjustable Paper Shredder', 81.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (345, 'OFFC-345', 'Space-Saving Desk Organizer', 217.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (346, 'OFFC-346', 'Compact Bookend Set', 149.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (347, 'OFFC-347', 'Rechargeable Label Maker', 263.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (348, 'OFFC-348', 'Portable Desk Mat', 319.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (349, 'OFFC-349', 'Multi-Function Presenter Remote', 98.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (350, 'OFFC-350', 'Executive Presenter Remote', 67.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (351, 'OFFC-351', 'Rechargeable Bookend Set', 268.00, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (352, 'OFFC-352', 'Executive Bookend Set', 49.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (353, 'OFFC-353', 'Ergonomic Bookend Set', 61.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (354, 'OFFC-354', 'Multi-Function Office Chair', 100.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (355, 'OFFC-355', 'Multi-Function Laptop Stand', 62.50, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (356, 'OFFC-356', 'LED Document Scanner', 103.99, 'Office');
INSERT INTO product (id, sku, name, unit_price, category) VALUES (357, 'OFFC-357', 'Rechargeable Bulletin Board', 287.99, 'Office');

-- Same fix as V3/V5/V14 -- an explicit-id INSERT never advances product_seq on its own.
SELECT setval('product_seq', (SELECT COALESCE(MAX(id), 1) FROM product));
