package com.learn.apigateway.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.convert.converter.Converter;
import org.springframework.http.HttpMethod;
import org.springframework.security.authentication.AbstractAuthenticationToken;
import org.springframework.security.config.annotation.web.reactive.EnableWebFluxSecurity;
import org.springframework.security.config.web.server.ServerHttpSecurity;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter;
import org.springframework.security.oauth2.server.resource.authentication.ReactiveJwtAuthenticationConverterAdapter;
import org.springframework.security.web.server.SecurityWebFilterChain;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.reactive.CorsConfigurationSource;
import org.springframework.web.cors.reactive.UrlBasedCorsConfigurationSource;
import reactor.core.publisher.Mono;

import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

// This is the entire authorization policy for the whole application, in one place: which
// routes need a token at all, and which need more than that. Order Service and Inventory
// Service have no security code whatsoever -- they trust that the only way to reach them
// is through this Gateway, which is only true because their ports stay off the public
// internet at the network level (see the EC2 security group). This class is what turns
// "hidden" into "actually authorized."
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {

    // Comma-separated via env var (ALLOWED_ORIGINS) the same way ORDER_SERVICE_URL etc.
    // are -- see corsConfigurationSource() for why this can no longer just be "*".
    @Value("${cors.allowed-origins}")
    private String[] allowedOrigins;

    @Bean
    public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
        return http
                // A pure API gateway with no browser session/forms has no CSRF-vulnerable state to
                // protect -- CSRF protection exists for cookie-based sessions, not Bearer tokens.
                .csrf(ServerHttpSecurity.CsrfSpec::disable)
                // CORS is wired in here (Spring Security's own CorsWebFilter), not just via Spring
                // Cloud Gateway's `globalcors` config -- that filter only runs once a request has
                // already been routed to a backend, i.e. only on responses to successfully
                // authenticated requests. A 401 (missing/expired/malformed token) is generated by
                // Security's own AuthenticationEntryPoint *before* routing ever happens, so it never
                // picked up a CORS header under the old setup -- the browser then reports that as a
                // bare "Failed to fetch" instead of a normal 401 the frontend can act on (e.g. log the
                // user out and send them back to /login). Wiring CORS in at this layer instead makes
                // it apply to every response this Gateway ever sends, success or failure.
                .cors(cors -> cors.configurationSource(corsConfigurationSource()))
                .authorizeExchange(exchanges -> exchanges
                        // CORS preflight requests never carry the Authorization header -- that's by
                        // design, the browser hasn't been told it's allowed to send it yet. Requiring
                        // auth on OPTIONS would reject every preflight, which silently blocks the real
                        // request too, since the browser never proceeds past a failed preflight.
                        .pathMatchers(HttpMethod.OPTIONS, "/**").permitAll()
                        // The Docker healthcheck (see docker-compose.prod.yml) calls this directly
                        // with plain wget, no token -- this is the Gateway's OWN Spring Security
                        // instance guarding requests to itself (separate from the auth it enforces
                        // on the routes it proxies to Order/Inventory Service), so without this rule
                        // the healthcheck would get a 401 and the Gateway would look permanently
                        // unhealthy regardless of whether it's actually fine.
                        .pathMatchers("/actuator/health").permitAll()
                        // Login has no token yet by definition; refresh only ever has the httpOnly
                        // cookie (no Bearer token); logout must still work against an
                        // already-expired access token. google/callback is the same "no token yet"
                        // case as login -- it's the request that's exchanging a Google/Cognito
                        // authorization code for the very first access token. See AuthController.
                        .pathMatchers(HttpMethod.POST, "/auth/login", "/auth/refresh", "/auth/logout", "/auth/google/callback").permitAll()
                        // Stock levels are admin-only information, full stop -- not just hidden in
                        // the frontend (ProductsPage/ProductDetailPage only render/fetch this for
                        // isAdmin), enforced here too so a non-admin genuinely can't see it, not
                        // merely isn't shown it. /stock/** (not just /stock/*/restock below) covers
                        // both the plain listing and the per-product lookup -- same wildcard the
                        // routing config below already relies on to match both /stock and /stock/{id}.
                        .pathMatchers(HttpMethod.GET, "/stock/**").hasAuthority("ROLE_admin")
                        // Most specific rule next: restock additionally requires the "admin" group.
                        // hasAuthority checks for the exact "ROLE_admin" authority our converter below
                        // produces from the token's cognito:groups claim.
                        .pathMatchers(HttpMethod.POST, "/stock/*/restock").hasAuthority("ROLE_admin")
                        // Same admin-only reasoning for product image uploads: any valid token can
                        // still read /products (see the final rule below), but only an admin can mint
                        // an upload URL, confirm one, or delete an image.
                        //
                        // Fixed a real gap here: the two rules below used to be a single
                        // `PUT /products/*/image` rule, which matched NO actual endpoint at all
                        // (ProductController's real routes are POST .../images and
                        // DELETE .../images/{imageId} -- plural, and never PUT). That meant both
                        // fell through to the generic "any authenticated user" rule at the bottom --
                        // any logged-in non-admin could attach or delete a product's images. Caught
                        // by actually reading this file against the controller's real @PostMapping/
                        // @DeleteMapping annotations, not by trusting the rule's own comment.
                        .pathMatchers(HttpMethod.POST, "/products/*/image-upload-url").hasAuthority("ROLE_admin")
                        .pathMatchers(HttpMethod.POST, "/products/*/images").hasAuthority("ROLE_admin")
                        .pathMatchers(HttpMethod.DELETE, "/products/*/images/*").hasAuthority("ROLE_admin")
                        // Same admin-only reasoning, same three-rule shape, for the one
                        // optional product video (ProductVideoUploadService/Product#videoUrl).
                        .pathMatchers(HttpMethod.POST, "/products/*/video-upload-url").hasAuthority("ROLE_admin")
                        .pathMatchers(HttpMethod.PUT, "/products/*/video").hasAuthority("ROLE_admin")
                        .pathMatchers(HttpMethod.DELETE, "/products/*/video").hasAuthority("ROLE_admin")
                        // Every other route just needs any validly-signed, unexpired token.
                        .anyExchange().authenticated()
                )
                .oauth2ResourceServer(oauth2 -> oauth2.jwt(jwt -> jwt.jwtAuthenticationConverter(jwtAuthenticationConverter())))
                .build();
    }

    // Used to allow any origin ("*") since only a Bearer token in a header was ever sent,
    // never cookies. That changed with the BFF (AuthController): /auth/login and
    // /auth/refresh now set/read an HttpOnly cookie, which means the browser must send
    // credentials with those requests -- and CORS flatly forbids combining
    // allowCredentials(true) with a wildcard origin (Spring itself refuses to start with
    // that combination). allowedOrigins now lists the exact origins the frontend is
    // actually served from instead: the CloudFront distribution in production, plus the
    // Vite dev server for local dev against a Gateway run outside Docker.
    private CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(List.of(allowedOrigins));
        configuration.setAllowedMethods(List.of("GET", "POST", "PUT", "DELETE", "OPTIONS"));
        configuration.setAllowedHeaders(List.of("*"));
        configuration.setAllowCredentials(true);
        // Unlike request headers, browsers only expose a small built-in safelist of
        // RESPONSE headers to JS by default -- a custom one like this needs to be listed
        // here explicitly, or `response.headers.get("X-Correlation-Id")` would silently
        // return null in the browser despite the header genuinely being on the wire (see
        // CorrelationIdFilter, which echoes it back on every response).
        configuration.setExposedHeaders(List.of(CorrelationIdFilter.CORRELATION_ID_HEADER));

        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }

    // Spring Security's default JWT->authorities mapping looks at "scope"/"scp" claims, which
    // Cognito access tokens don't meaningfully use here. This reads Cognito's own
    // "cognito:groups" claim instead and turns each group into a "ROLE_<group>" authority --
    // e.g. the "admin" group becomes "ROLE_admin", which is exactly what hasAuthority above checks.
    private Converter<Jwt, Mono<AbstractAuthenticationToken>> jwtAuthenticationConverter() {
        Converter<Jwt, Collection<GrantedAuthority>> groupsConverter = jwt -> {
            List<String> groups = jwt.getClaimAsStringList("cognito:groups");
            if (groups == null) {
                return List.of();
            }
            return groups.stream()
                    .<GrantedAuthority>map(group -> new SimpleGrantedAuthority("ROLE_" + group))
                    .collect(Collectors.toList());
        };

        JwtAuthenticationConverter delegate = new JwtAuthenticationConverter();
        delegate.setJwtGrantedAuthoritiesConverter(groupsConverter);

        // Spring Cloud Gateway runs on WebFlux (reactive), but JwtAuthenticationConverter is the
        // plain (non-reactive) Spring Security type -- this adapter wraps it into the Mono-returning
        // shape the reactive resource server actually needs.
        return new ReactiveJwtAuthenticationConverterAdapter(delegate);
    }
}
